name: xplorit
description: "Rent with Ease."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.5.6
  connectivity_plus: ^5.0.2
  firebase_core: ^2.24.2

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  smooth_page_indicator: ^1.1.0
  intl_phone_number_input: ^0.7.4
  table_calendar: ^3.0.9
  quickalert: ^1.0.2
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  pinput: ^4.0.0
  google_maps_flutter: ^2.5.3
  location: ^5.0.0
  flutter_polyline_points: ^2.0.0
  awesome_snackbar_content: 0.1.1
  firebase_app_check: ^0.2.2+7
  
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  google_sign_in: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.0.0
  image_picker: ^1.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo.png"
  image_path_android: "assets/logos/logo.png"
  image_path_ios: "assets/logos/logo.png"
  adaptive_icon_forground: "assets/logos/logo_forground.png"
  adaptive_icon_background: "#ffffff"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/logos/logolight.png
  image_dark: assets/logos/logodark.png

android_12:
  icon_background_color: "#f7f6f1"
  icon_background_color_dark: "#272727"
  image: assets/images/logolight.png
  image_dark: assets/logos/logolight.png

flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/vehicles/
    - assets/images/payment_methods/
    - assets/icons/
    - assets/icons/vehicle-icons/
    - assets/icons/action-icons/
    - assets/logos/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-Black.ttf
        - asset: assets/fonts/Lexend/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend/Lexend-ExtraBold.ttf
        - asset: assets/fonts/Lexend/Lexend-ExtraLight.ttf
        - asset: assets/fonts/Lexend/Lexend-Light.ttf
        - asset: assets/fonts/Lexend/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend/Lexend-SemiBold.ttf
        - asset: assets/fonts/Lexend/Lexend-Thin.ttf
          
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf

